### ISSUE TITLE
Disappearing implants in rimworld 1.5 and Severity

### ISSUE THREAD

**Issue by Graph-Donte-Crypto** [ISOR3X/communityframework#15]
Hello

I don't know if this problem existed before, but I found it in several mods that add implants to rimworld 1.5. The point is that if an implant uses Severity to calculate something and sets the Severity value to 0, then the implant disappears, since rimworld uses Severity, among other things, to remove diseases and so on (as far as I understand)

For example, if the HediffComp_SeverityFromSkill or HediffComp_SeverityFromPain components are used, they can set the Severity value to 0, after which the implant will simply disappear, without a log or error

Specifically, in the mod that I am using now, the author and I made a hotfix, replacing your components with their own analogs that set not 0, but 0.01

But in general, I think it would be nice if it were possible to somehow specify in the xml configuration that even if Severity = 0, then hediff does not need to be removed

So far I do not know how to do this except with the Harmony patch, so I would be grateful if you direct me :)

P.S. English is not my native language, so the translation may not be accurate

**Comment by Turnovus** [comment]
Confirmed, can be replicated.
