### ISSUE TITLE
[Feature Request] Additional tags for HediffCompProperties_MultiplyOtherHediff

### ISSUE THREAD

**Issue by kaedys** [ISOR3X/communityframework#9]
The MultiplyOtherHediff comp appears to only affect the duration of _new_ hediffs added after the affecting hediff is present.  Could an additional tag (ex. `<affectExisting>`) be added to the comp to specify whether _existing_ instances of the affected hediffs should also have their duration and/or severity affected?  Example use-case would be administering Wake-up to a pawn after surgery to immediately reduce the severity of their existing Anesthetic hediff from that surgery, and thereby wake them up.

**Comment by Turnovus** [comment]
That sounds completely feasible, I'll look into adding it after the D9 merge is complete.

**Comment by kaedys** [comment]
@Turnovus did this end up getting implemented at some point?  Been a bit since I was messing with Rimworld mods, but it's probably on the horizon for me again soon, and I'd love to see this implemented.  The newest use-case is a gene I created that reduces the duration of gene-shock and gene-regrowing (designed to be injected into prisoners you want to chain-extract, and a few other purposes).  But since inserting that gene causes the gene regrowth _before_ the new hediff from the injected gene is applied (at least, last time I checked), you have to wait out the full duration of the shock from inserting the gene that...reduces the duration of the gene shock.  This would allow that gene to immediately reduce the duration of it.

**Comment by Turnovus** [comment]
@kaedys 
Not yet, I'll add it to the current development branch when I get a chance.
